name: Sync with upstream

on:
  schedule:
    - cron: '0 * * * *'  # 每小时检查一次更新
  workflow_dispatch:  # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout This Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Add Upstream Repository
        run: |
          git remote add upstream https://github.com/wy876/POC.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          
      - name: Push Changes to Fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
